---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 80, host: 8001, auto_correct: true }]
    - ["forwarded_port", { guest: 443, host: 4431, auto_correct: true }]
provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
    attributes:
      firewall:
        allow_ssh: true
suites:
  - name: default
    run_list:
      - recipe[gina_id::default]
    attributes:
      app:
        ssl_data_bag: ''
      acme:
        endpoint: https://acme-staging.ap.letsencrypt.org
