---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 80, host: 8000 }]
    - ["forwarded_port", { guest: 443, host: 4430 }]
provisioner:
  name: chef_zero
  data_bags_path: ~/.chef/data_bags/

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[gina_id::default]
    attributes:
