---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 80, host: 8001 }]
    - ["forwarded_port", { guest: 443, host: 4431 }]
provisioner:
  name: chef_zero

platforms:
  - name: bento/centos-6.7

suites:
  - name: default
    run_list:
      - recipe[gina_id::default]
    attributes:
      app:
        ssl_data_bag: ''
